object ScreenForm: TScreenForm
  Left = 0
  Top = 0
  BorderStyle = bsNone
  ClientHeight = 768
  ClientWidth = 1024
  Color = clCream
  TransparentColor = True
  TransparentColorValue = clCream
  Font.Charset = HANGEUL_CHARSET
  Font.Color = clWindowText
  Font.Height = -15
  Font.Name = #47569#51008' '#44256#46357
  Font.Style = []
  Position = poDesigned
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnShow = FormShow
  TextHeight = 20
  object pgcScreen: TcxPageControl
    Left = 0
    Top = 0
    Width = 1024
    Height = 768
    Color = clBlack
    ParentBackground = False
    ParentColor = False
    TabOrder = 0
    Properties.ActivePage = tabHome
    Properties.ActivateFocusedTab = False
    Properties.CustomButtons.Buttons = <>
    LookAndFeel.Kind = lfUltraFlat
    LookAndFeel.NativeStyle = False
    ClientRectBottom = 768
    ClientRectRight = 1024
    ClientRectTop = 31
    object tabHome: TcxTabSheet
      Caption = #54856
      Color = 2236979
      ImageIndex = 0
      ParentColor = False
      object imgHome: TcxImage
        Left = 0
        Top = 0
        Align = alClient
        Properties.FitMode = ifmNormal
        Properties.ShowFocusRect = False
        Style.BorderColor = 2236979
        Style.BorderStyle = ebsNone
        Style.Color = 2236979
        Style.Edges = []
        Style.LookAndFeel.NativeStyle = False
        StyleDisabled.BorderColor = 2236979
        StyleDisabled.Color = 2236979
        StyleDisabled.LookAndFeel.NativeStyle = False
        StyleFocused.BorderStyle = ebsNone
        StyleFocused.LookAndFeel.NativeStyle = False
        StyleHot.BorderStyle = ebsNone
        StyleHot.LookAndFeel.NativeStyle = False
        TabOrder = 0
        Height = 737
        Width = 1024
      end
    end
    object tabMedia: TcxTabSheet
      Caption = #53080#53584#52768' '#51116#49373
      Color = 2236979
      ImageIndex = 1
      ParentColor = False
      ExplicitTop = 0
      ExplicitWidth = 0
      ExplicitHeight = 0
      object PicShow: TPicShow
        Left = 0
        Top = 0
        Width = 1024
        Height = 737
        Align = alClient
        AutoSize = True
        BevelInner = bvNone
        BevelOuter = bvNone
        BgMode = bmCentered
        Center = True
        Color = clBlack
        ParentColor = False
        TabOrder = 0
      end
      object VideoPlayer: TVideoGrabber
        Left = 0
        Top = 0
        Width = 1024
        Height = 737
        Align = alClient
        Color = clBlack
        AnalogVideoStandard = 0
        AspectRatioToUse = -1.000000000000000000
        AudioCompressor = 0
        AudioInput = 0
        AutoFileNameDateTimeFormat = 'yymmdd_hhmmss_zzz'
        AutoFilePrefix = 'vg'
        BorderStyle = bsNone
        Cropping_Zoom = 1.000000000000000000
        ImageOverlayEnabled = False
        ImageOverlay_AlphaBlend = False
        ImageOverlay_AlphaBlendValue = 180
        ImageOverlay_ChromaKey = False
        ImageOverlay_ChromaKeyLeewayPercent = 25
        ImageOverlay_ChromaKeyRGBColor = 0
        ImageOverlay_Height = -1
        ImageOverlay_LeftLocation = 10
        ImageOverlay_VideoAlignment = oa_LeftTop
        ImageOverlay_StretchToVideoSize = False
        ImageOverlay_TopLocation = 10
        ImageOverlay_Transparent = False
        ImageOverlay_TransparentColorValue = 0
        ImageOverlay_UseTransparentColor = False
        ImageOverlay_Width = -1
        ImageOverlay_TargetDisplay = -1
        LicenseString = 'N/A'
        MotionDetector_Grid = 
          '5555555555 5555555555 5555555555 5555555555 5555555555 555555555' +
          '5 5555555555 5555555555 5555555555 5555555555'
        NDIName = 'DATASTEAD_UNNAMED_SOURCE'
        PlayerSpeedRatio = 1.000000000000000000
        TextOverlay_Enabled = False
        TextOverlay_Font.Charset = DEFAULT_CHARSET
        TextOverlay_Font.Color = clAqua
        TextOverlay_Font.Height = -16
        TextOverlay_Font.Name = 'Arial'
        TextOverlay_Font.Style = []
        TextOverlay_FontColor = clAqua
        TextOverlay_FontSize = 12
        TextOverlay_HighResFont = True
        TextOverlay_Left = 0
        TextOverlay_Top = 0
        TextOverlay_Right = -1
        TextOverlay_Orientation = to_Horizontal
        TextOverlay_Scrolling = False
        TextOverlay_ScrollingSpeed = 1
        TextOverlay_Shadow = True
        TextOverlay_ShadowColor = clBlack
        TextOverlay_ShadowDirection = cd_SouthEast
        TextOverlay_BkColor = clWhite
        TextOverlay_Align = tf_Left
        TextOverlay_AlphaBlend = False
        TextOverlay_AlphaBlendValue = 180
        TextOverlay_GradientMode = gm_Disabled
        TextOverlay_GradientColor = clNavy
        TextOverlay_VideoAlignment = oa_LeftTop
        TextOverlay_String = 
          'Note: the date/time formats '#13#10'can be easily modified.'#13#10#13#10'system ' +
          'date/time: %sys_time[dd/mm/yy hh:nn:ss]%'#13#10'DV time code: %time_co' +
          'de%'#13#10'DV date/time: %dv_time[dd/mm/yy hh:nn:ss]%'#13#10'frame number: %' +
          'frame_count%'#13#10'time (full): %time_full%'#13#10'time (sec): %time_sec%'#13#10 +
          'time (ns): %time_100ns%'
        TextOverlay_TargetDisplay = -1
        TextOverlay_Transparent = True
        v360_AspectRatio = -1.000000000000000000
        VideoCompression_Quality = 1.000000000000000000
        VideoCompressor = 0
        VideoDelay = 0
        VideoFormat = 0
        VideoFromImages_TemporaryFile = 'SetOfBitmaps01.dat'
        VideoInput = 0
        VideoProcessing_RotationCustomAngle = 45.500000000000000000
        VideoSize = 0
        StreamInterface_Format = 'mpegts'
        StreamInterface_IsRealTime = True
        VideoSubtype = 0
        OnLog = VideoPlayerLog
        OnPlayerStateChanged = VideoPlayerPlayerStateChanged
      end
    end
  end
  object panRemainTime: TPanel
    Left = 20
    Top = 48
    Width = 150
    Height = 64
    Cursor = crHandPoint
    BevelOuter = bvNone
    Caption = '00:00'
    Color = 11520
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -40
    Font.Name = 'Impact'
    Font.Style = []
    Padding.Left = 10
    Padding.Top = 5
    Padding.Right = 10
    Padding.Bottom = 5
    ParentBackground = False
    ParentFont = False
    TabOrder = 1
    OnMouseDown = panRemainTimeMouseDown
  end
end
